package com.example.lmsbackend.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum StatusCode {
    SUCCESS("Thành công"),
    UNHANDLED_EXCEPTION("Unhandled exception -> Should write exception handler to handle it"),
    UNAUTHORIZED("Không có quyền."),
    FORBIDDEN("Không có quyền"),
    SQL("Sql error"),
    INVALID_INPUT("Giá trị nhập không hợp lệ"),
    REPASSWORD_NOT_EQUALS_PASSWORD("Phần nhập lại mật khẩu không khớp với mật khẩu"),
    USERNAME_EXISTED("Tên đăng nhập đã được sử dụng"),
    USERNAME_EMPTY("Tên đăng nhập rỗng"),
    USER_NOT_FOUND("Người dùng không tồn tại"),
    INCORRECT_PASSWORD("Mật khẩu không đúng"),
    DOMAIN_ALREADY_EXISTS("Workspace đã được đăng ký"),
    JWT_EXPIRES("Jwt has expired"),
    JWT_INVALID("Jwt is invalid"),
    EXPIRED_SHARE_FILE_TOKEN("Mã share file đã hết hạn"),
    INVALID_SHARE_FILE_TOKEN("Mã share file không hợp lệ"),
    PROGRAM_NOT_FOUND("Không tìm thấy chương trình"),
    PROGRAM_CODE_ALREADY_EXISTS("Mã chương trình đã được sử dụng"),
    CLASS_CODE_ALREADY_EXISTS("Mã lớp này đã được sử dụng"),
    CLASS_NOT_FOUND("Không tìm thấy lớp"),
    COURSE_CODE_ALREADY_EXISTS("Mã khóa học đã được sử dụng"),
    MEMBER_ALREADY_IN_CLASS("Thành viên này đã tồn tại trong lớp"),
    ROLE_NOT_FOUND("Không tìm thấy vai trò này"),
    STAFF_NOT_FOUND("Không tìm thấy nhân viên này"),
    NOTIFICATION_NOT_FOUND("Không tìm thấy thông báo này"),
    CANNOT_CREATE_DOMAIN_EXCEPTION("Không thể tạo workspace"),
    EXAM_NOT_FOUND("Không tìm thấy bài kiểm tra, vui lòng tải lại trang để cập nhật dữ liệu"),
    UNSUPPORTED_QUESTION_TYPE("Không hỗ trợ loại câu hỏi này"),
    TEXTBOOK_NOT_FOUND("Không tìm thấy tài liệu này"),
    EXAM_INSTANCE_HAS_NOT_CONFIGURED_YET("This exam instance hasn't configure, it means the manager hasn't add this quiz to class."),
    EXAM_INSTANCE_HAS_ALREADY_CLOSED("Bài quiz này đã quá hạn, vui lòng liên hệ giáo viên để được hỗ trợ"),
    QUIZ_NOT_FOUND_IN_CLASS("Không tìm thấy quiz trong lớp"),
    FINISHED_TIME_NOT_VALID("Finished time is not valid"),
    EXAM_HAS_NOT_SCORED_FOR_STUDENT("This session hasn't been scored by system"),
    EXAM_INSTANCE_IS_NOT_FULLY_CONFIGURED("This exam instance is not fully configured"),
    EXAM_SESSION_EXPIRED("Quiz đã hết thời gian làm bài. Vui lòng refresh lại trang."),
    STUDENT_NOT_FOUND_EXCEPTION("Không tìm thấy học sinh này"),
    EMAIL_USED_EXCEPTION("Email này đã được sử dụng."),
    DRAG_AND_DROP_IS_NOT_ALLOWED("Drag and drop is not allowed because there are active class which belong to this course"),
    ADD_CHOICE_IS_NOT_ALLOWED("Student is not allowed to add choices to voting"),
    VOTING_NOT_FOUND("Không tìm thấy bình chọn này"),
    VOTING_CHOICE_NOT_FOUND("Không tìm thấy lượt bình chọn này"),
    USER_IS_NOT_ALLOWED_TO_UPDATE_VOTING_CHOICE("Không được phép cập nhật lượt bình chọn"),
    POST_NOT_FOUND("Không tìm thấy bài viết"),
    COMMENT_NOT_FOUND("Không tìm thấy bình luận"),
    QUIZ_IS_NOT_ALLOWED_TO_PUBLISH("Không có quyền hiển thị quiz này"),
    UNSUPPORTED_CONTENT_TYPE("Không hỗ trợ loại này"),
    CHAPTER_NOT_FOUND("Không tìm thấy chương này"),
    SESSION_HAS_NOT_ENDED("Session này đã kết thúc"),
    STUDENT_HAS_ALREADY_IN_CLASS("Học sinh này đã tham gia lớp học"),
    TEACHER_HAS_ALREADY_IN_CLASS("Giáo viên này đang dạy lớp này rồi"),
    TEACHER_NOT_FOUND_IN_CLASS("Giáo viên này không dạy lớp vừa chọn"),
    SCORING_MANUALLY_NOT_SUPPORTED("Question type is not supported for scoring manually"),
    USER_IS_NOT_STUDENT_OF_CLASS("Học sinh không thuộc lớp học"),
    CLASS_SESSION_NOT_FOUND("The class session is not found"),
    SUMMARY_ATTENDANCE_CANNOT_BE_DELETED("The summary attendance of each session can not be deleted"),
    GRADE_TAG_NOT_FOUND("Không tìm thấy cột điểm này"),
    QUIZ_SESSION_NOT_FOUND("Quiz session is not found"),
    QUIZ_SESSION_ENDED("Quiz session has ended"),
    VERIFY_URL_INVALID_EXCEPTION("Link xác thực không hợp lệ"),
    PRIMITIVE_TAG_EXCEPTION("Điểm của cột này có được từ quá trình làm bài của học sinh, không thực hiện được hành động vừa chọn."),
    GRADE_FORMULA_NOT_FOUND("Không tìm thấy công thức tính điểm"),
    QUIZ_ATTEMPT_REACH_LIMIT("Bạn đã làm hết số lần qui định, vui lòng liên hệ giáo viên để được hỗ trợ thêm"),
    PACKAGE_NOT_FOUND("Gói vừa chọn không được cung cấp"),
    DELETE_DEFAULT_ROLE_EXCEPTION("Đây là vai trò mặc định của hệ thống, bạn không được phép xóa role này."),
    USERNAME_OR_PASSWORD_INCORRECT("Tên đăng nhập hoặc tài khoản không chính xác."),
    COURSE_HAS_CLASS_OPENED("Khóa này đã được mở lớp."),
    EXAM_BEING_USED("Không thể xóa vì đề đang được sử dụng trong các bài quiz"),
    EXISTING_UNENDED_QUIZ_SESSION("Không thể bắt đầu lần làm bài mới vì bạn chưa kết thúc lần làm bài trước đó"),
    UNABLE_CONFIGURE_QUIZ("Không thể thiết lập cho bài kiểm tra vì đang ở trạng thái cho học sinh làm bài"),
    POINT_INVALID("Điểm cho học sinh không thể lớn hơn điểm của câu hỏi"),
    INVALID_ACTION_WITH_PRIMITIVE_GRADE_TAG("Hành động này không được phép thực hiện với cột điểm gốc."),

    FIlE_HAS_ERROR("Không đọc được file, vui lòng kiểm tra và thử lại."),
    NOT_ENOUGH_GRADE_EXCEPTION(""),
    UPDATE_QUIZ_EXCEPTION(""),
    INVALID_CHANGE_ATTENDANCE("Không được thay đổi trạng thái điểm danh của buổi học chưa diễn ra")
    ;
    private final String message;
}
