version: '3.8'

services:
  db:
    image: postgres:10
    container_name: lms
    restart: always
    volumes:
      - lms-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sq
    environment:
      POSTGRES_DB: lms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lms
    ports:
      - "5432:5432"
  redis:
    image: "redis"
    container_name: redis
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: redis

volumes:
  lms-data:
    name: lms-data