// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"lms-class/ent/examhistory"
	"lms-class/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExamHistoryDelete is the builder for deleting a ExamHistory entity.
type ExamHistoryDelete struct {
	config
	hooks    []Hook
	mutation *ExamHistoryMutation
}

// Where appends a list predicates to the ExamHistoryDelete builder.
func (ehd *ExamHistoryDelete) Where(ps ...predicate.ExamHistory) *ExamHistoryDelete {
	ehd.mutation.Where(ps...)
	return ehd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ehd *ExamHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ehd.sqlExec, ehd.mutation, ehd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ehd *ExamHistoryDelete) ExecX(ctx context.Context) int {
	n, err := ehd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ehd *ExamHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(examhistory.Table, sqlgraph.NewFieldSpec(examhistory.FieldID, field.TypeInt))
	if ps := ehd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ehd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ehd.mutation.done = true
	return affected, err
}

// ExamHistoryDeleteOne is the builder for deleting a single ExamHistory entity.
type ExamHistoryDeleteOne struct {
	ehd *ExamHistoryDelete
}

// Where appends a list predicates to the ExamHistoryDelete builder.
func (ehdo *ExamHistoryDeleteOne) Where(ps ...predicate.ExamHistory) *ExamHistoryDeleteOne {
	ehdo.ehd.mutation.Where(ps...)
	return ehdo
}

// Exec executes the deletion query.
func (ehdo *ExamHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := ehdo.ehd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{examhistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ehdo *ExamHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := ehdo.Exec(ctx); err != nil {
		panic(err)
	}
}
