// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lms-class/ent/exam"
	"lms-class/ent/predicate"
	"lms-class/ent/quiz"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExamUpdate is the builder for updating Exam entities.
type ExamUpdate struct {
	config
	hooks    []Hook
	mutation *ExamMutation
}

// Where appends a list predicates to the ExamUpdate builder.
func (eu *ExamUpdate) Where(ps ...predicate.Exam) *ExamUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetTitle sets the "title" field.
func (eu *ExamUpdate) SetTitle(s string) *ExamUpdate {
	eu.mutation.SetTitle(s)
	return eu
}

// SetContext sets the "context" field.
func (eu *ExamUpdate) SetContext(s string) *ExamUpdate {
	eu.mutation.SetContext(s)
	return eu
}

// SetContextId sets the "contextId" field.
func (eu *ExamUpdate) SetContextId(s string) *ExamUpdate {
	eu.mutation.SetContextId(s)
	return eu
}

// SetIsPublished sets the "isPublished" field.
func (eu *ExamUpdate) SetIsPublished(b bool) *ExamUpdate {
	eu.mutation.SetIsPublished(b)
	return eu
}

// SetHavingDraft sets the "havingDraft" field.
func (eu *ExamUpdate) SetHavingDraft(b bool) *ExamUpdate {
	eu.mutation.SetHavingDraft(b)
	return eu
}

// SetLastPublishedAt sets the "lastPublishedAt" field.
func (eu *ExamUpdate) SetLastPublishedAt(t time.Time) *ExamUpdate {
	eu.mutation.SetLastPublishedAt(t)
	return eu
}

// SetNillableLastPublishedAt sets the "lastPublishedAt" field if the given value is not nil.
func (eu *ExamUpdate) SetNillableLastPublishedAt(t *time.Time) *ExamUpdate {
	if t != nil {
		eu.SetLastPublishedAt(*t)
	}
	return eu
}

// ClearLastPublishedAt clears the value of the "lastPublishedAt" field.
func (eu *ExamUpdate) ClearLastPublishedAt() *ExamUpdate {
	eu.mutation.ClearLastPublishedAt()
	return eu
}

// SetUpdatedAt sets the "updatedAt" field.
func (eu *ExamUpdate) SetUpdatedAt(t time.Time) *ExamUpdate {
	eu.mutation.SetUpdatedAt(t)
	return eu
}

// AddQuizIDs adds the "quizzes" edge to the Quiz entity by IDs.
func (eu *ExamUpdate) AddQuizIDs(ids ...int) *ExamUpdate {
	eu.mutation.AddQuizIDs(ids...)
	return eu
}

// AddQuizzes adds the "quizzes" edges to the Quiz entity.
func (eu *ExamUpdate) AddQuizzes(q ...*Quiz) *ExamUpdate {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return eu.AddQuizIDs(ids...)
}

// Mutation returns the ExamMutation object of the builder.
func (eu *ExamUpdate) Mutation() *ExamMutation {
	return eu.mutation
}

// ClearQuizzes clears all "quizzes" edges to the Quiz entity.
func (eu *ExamUpdate) ClearQuizzes() *ExamUpdate {
	eu.mutation.ClearQuizzes()
	return eu
}

// RemoveQuizIDs removes the "quizzes" edge to Quiz entities by IDs.
func (eu *ExamUpdate) RemoveQuizIDs(ids ...int) *ExamUpdate {
	eu.mutation.RemoveQuizIDs(ids...)
	return eu
}

// RemoveQuizzes removes "quizzes" edges to Quiz entities.
func (eu *ExamUpdate) RemoveQuizzes(q ...*Quiz) *ExamUpdate {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return eu.RemoveQuizIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *ExamUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, eu.sqlSave, eu.mutation, eu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eu *ExamUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *ExamUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *ExamUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (eu *ExamUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(exam.Table, exam.Columns, sqlgraph.NewFieldSpec(exam.FieldID, field.TypeInt))
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.Title(); ok {
		_spec.SetField(exam.FieldTitle, field.TypeString, value)
	}
	if value, ok := eu.mutation.Context(); ok {
		_spec.SetField(exam.FieldContext, field.TypeString, value)
	}
	if value, ok := eu.mutation.ContextId(); ok {
		_spec.SetField(exam.FieldContextId, field.TypeString, value)
	}
	if value, ok := eu.mutation.IsPublished(); ok {
		_spec.SetField(exam.FieldIsPublished, field.TypeBool, value)
	}
	if value, ok := eu.mutation.HavingDraft(); ok {
		_spec.SetField(exam.FieldHavingDraft, field.TypeBool, value)
	}
	if value, ok := eu.mutation.LastPublishedAt(); ok {
		_spec.SetField(exam.FieldLastPublishedAt, field.TypeTime, value)
	}
	if eu.mutation.LastPublishedAtCleared() {
		_spec.ClearField(exam.FieldLastPublishedAt, field.TypeTime)
	}
	if value, ok := eu.mutation.UpdatedAt(); ok {
		_spec.SetField(exam.FieldUpdatedAt, field.TypeTime, value)
	}
	if eu.mutation.QuizzesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.QuizzesTable,
			Columns: []string{exam.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.RemovedQuizzesIDs(); len(nodes) > 0 && !eu.mutation.QuizzesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.QuizzesTable,
			Columns: []string{exam.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.QuizzesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.QuizzesTable,
			Columns: []string{exam.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{exam.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	eu.mutation.done = true
	return n, nil
}

// ExamUpdateOne is the builder for updating a single Exam entity.
type ExamUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExamMutation
}

// SetTitle sets the "title" field.
func (euo *ExamUpdateOne) SetTitle(s string) *ExamUpdateOne {
	euo.mutation.SetTitle(s)
	return euo
}

// SetContext sets the "context" field.
func (euo *ExamUpdateOne) SetContext(s string) *ExamUpdateOne {
	euo.mutation.SetContext(s)
	return euo
}

// SetContextId sets the "contextId" field.
func (euo *ExamUpdateOne) SetContextId(s string) *ExamUpdateOne {
	euo.mutation.SetContextId(s)
	return euo
}

// SetIsPublished sets the "isPublished" field.
func (euo *ExamUpdateOne) SetIsPublished(b bool) *ExamUpdateOne {
	euo.mutation.SetIsPublished(b)
	return euo
}

// SetHavingDraft sets the "havingDraft" field.
func (euo *ExamUpdateOne) SetHavingDraft(b bool) *ExamUpdateOne {
	euo.mutation.SetHavingDraft(b)
	return euo
}

// SetLastPublishedAt sets the "lastPublishedAt" field.
func (euo *ExamUpdateOne) SetLastPublishedAt(t time.Time) *ExamUpdateOne {
	euo.mutation.SetLastPublishedAt(t)
	return euo
}

// SetNillableLastPublishedAt sets the "lastPublishedAt" field if the given value is not nil.
func (euo *ExamUpdateOne) SetNillableLastPublishedAt(t *time.Time) *ExamUpdateOne {
	if t != nil {
		euo.SetLastPublishedAt(*t)
	}
	return euo
}

// ClearLastPublishedAt clears the value of the "lastPublishedAt" field.
func (euo *ExamUpdateOne) ClearLastPublishedAt() *ExamUpdateOne {
	euo.mutation.ClearLastPublishedAt()
	return euo
}

// SetUpdatedAt sets the "updatedAt" field.
func (euo *ExamUpdateOne) SetUpdatedAt(t time.Time) *ExamUpdateOne {
	euo.mutation.SetUpdatedAt(t)
	return euo
}

// AddQuizIDs adds the "quizzes" edge to the Quiz entity by IDs.
func (euo *ExamUpdateOne) AddQuizIDs(ids ...int) *ExamUpdateOne {
	euo.mutation.AddQuizIDs(ids...)
	return euo
}

// AddQuizzes adds the "quizzes" edges to the Quiz entity.
func (euo *ExamUpdateOne) AddQuizzes(q ...*Quiz) *ExamUpdateOne {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return euo.AddQuizIDs(ids...)
}

// Mutation returns the ExamMutation object of the builder.
func (euo *ExamUpdateOne) Mutation() *ExamMutation {
	return euo.mutation
}

// ClearQuizzes clears all "quizzes" edges to the Quiz entity.
func (euo *ExamUpdateOne) ClearQuizzes() *ExamUpdateOne {
	euo.mutation.ClearQuizzes()
	return euo
}

// RemoveQuizIDs removes the "quizzes" edge to Quiz entities by IDs.
func (euo *ExamUpdateOne) RemoveQuizIDs(ids ...int) *ExamUpdateOne {
	euo.mutation.RemoveQuizIDs(ids...)
	return euo
}

// RemoveQuizzes removes "quizzes" edges to Quiz entities.
func (euo *ExamUpdateOne) RemoveQuizzes(q ...*Quiz) *ExamUpdateOne {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return euo.RemoveQuizIDs(ids...)
}

// Where appends a list predicates to the ExamUpdate builder.
func (euo *ExamUpdateOne) Where(ps ...predicate.Exam) *ExamUpdateOne {
	euo.mutation.Where(ps...)
	return euo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *ExamUpdateOne) Select(field string, fields ...string) *ExamUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Exam entity.
func (euo *ExamUpdateOne) Save(ctx context.Context) (*Exam, error) {
	return withHooks(ctx, euo.sqlSave, euo.mutation, euo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (euo *ExamUpdateOne) SaveX(ctx context.Context) *Exam {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *ExamUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *ExamUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (euo *ExamUpdateOne) sqlSave(ctx context.Context) (_node *Exam, err error) {
	_spec := sqlgraph.NewUpdateSpec(exam.Table, exam.Columns, sqlgraph.NewFieldSpec(exam.FieldID, field.TypeInt))
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Exam.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, exam.FieldID)
		for _, f := range fields {
			if !exam.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != exam.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.Title(); ok {
		_spec.SetField(exam.FieldTitle, field.TypeString, value)
	}
	if value, ok := euo.mutation.Context(); ok {
		_spec.SetField(exam.FieldContext, field.TypeString, value)
	}
	if value, ok := euo.mutation.ContextId(); ok {
		_spec.SetField(exam.FieldContextId, field.TypeString, value)
	}
	if value, ok := euo.mutation.IsPublished(); ok {
		_spec.SetField(exam.FieldIsPublished, field.TypeBool, value)
	}
	if value, ok := euo.mutation.HavingDraft(); ok {
		_spec.SetField(exam.FieldHavingDraft, field.TypeBool, value)
	}
	if value, ok := euo.mutation.LastPublishedAt(); ok {
		_spec.SetField(exam.FieldLastPublishedAt, field.TypeTime, value)
	}
	if euo.mutation.LastPublishedAtCleared() {
		_spec.ClearField(exam.FieldLastPublishedAt, field.TypeTime)
	}
	if value, ok := euo.mutation.UpdatedAt(); ok {
		_spec.SetField(exam.FieldUpdatedAt, field.TypeTime, value)
	}
	if euo.mutation.QuizzesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.QuizzesTable,
			Columns: []string{exam.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.RemovedQuizzesIDs(); len(nodes) > 0 && !euo.mutation.QuizzesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.QuizzesTable,
			Columns: []string{exam.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.QuizzesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exam.QuizzesTable,
			Columns: []string{exam.QuizzesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quiz.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Exam{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{exam.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	euo.mutation.done = true
	return _node, nil
}
