// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"lms-class/ent/predicate"
	"lms-class/ent/questionhistory"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuestionHistoryQuery is the builder for querying QuestionHistory entities.
type QuestionHistoryQuery struct {
	config
	ctx        *QueryContext
	order      []questionhistory.OrderOption
	inters     []Interceptor
	predicates []predicate.QuestionHistory
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the QuestionHistoryQuery builder.
func (qhq *QuestionHistoryQuery) Where(ps ...predicate.QuestionHistory) *QuestionHistoryQuery {
	qhq.predicates = append(qhq.predicates, ps...)
	return qhq
}

// Limit the number of records to be returned by this query.
func (qhq *QuestionHistoryQuery) Limit(limit int) *QuestionHistoryQuery {
	qhq.ctx.Limit = &limit
	return qhq
}

// Offset to start from.
func (qhq *QuestionHistoryQuery) Offset(offset int) *QuestionHistoryQuery {
	qhq.ctx.Offset = &offset
	return qhq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (qhq *QuestionHistoryQuery) Unique(unique bool) *QuestionHistoryQuery {
	qhq.ctx.Unique = &unique
	return qhq
}

// Order specifies how the records should be ordered.
func (qhq *QuestionHistoryQuery) Order(o ...questionhistory.OrderOption) *QuestionHistoryQuery {
	qhq.order = append(qhq.order, o...)
	return qhq
}

// First returns the first QuestionHistory entity from the query.
// Returns a *NotFoundError when no QuestionHistory was found.
func (qhq *QuestionHistoryQuery) First(ctx context.Context) (*QuestionHistory, error) {
	nodes, err := qhq.Limit(1).All(setContextOp(ctx, qhq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{questionhistory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (qhq *QuestionHistoryQuery) FirstX(ctx context.Context) *QuestionHistory {
	node, err := qhq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first QuestionHistory ID from the query.
// Returns a *NotFoundError when no QuestionHistory ID was found.
func (qhq *QuestionHistoryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = qhq.Limit(1).IDs(setContextOp(ctx, qhq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{questionhistory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (qhq *QuestionHistoryQuery) FirstIDX(ctx context.Context) int {
	id, err := qhq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single QuestionHistory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one QuestionHistory entity is found.
// Returns a *NotFoundError when no QuestionHistory entities are found.
func (qhq *QuestionHistoryQuery) Only(ctx context.Context) (*QuestionHistory, error) {
	nodes, err := qhq.Limit(2).All(setContextOp(ctx, qhq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{questionhistory.Label}
	default:
		return nil, &NotSingularError{questionhistory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (qhq *QuestionHistoryQuery) OnlyX(ctx context.Context) *QuestionHistory {
	node, err := qhq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only QuestionHistory ID in the query.
// Returns a *NotSingularError when more than one QuestionHistory ID is found.
// Returns a *NotFoundError when no entities are found.
func (qhq *QuestionHistoryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = qhq.Limit(2).IDs(setContextOp(ctx, qhq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{questionhistory.Label}
	default:
		err = &NotSingularError{questionhistory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (qhq *QuestionHistoryQuery) OnlyIDX(ctx context.Context) int {
	id, err := qhq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of QuestionHistories.
func (qhq *QuestionHistoryQuery) All(ctx context.Context) ([]*QuestionHistory, error) {
	ctx = setContextOp(ctx, qhq.ctx, "All")
	if err := qhq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*QuestionHistory, *QuestionHistoryQuery]()
	return withInterceptors[[]*QuestionHistory](ctx, qhq, qr, qhq.inters)
}

// AllX is like All, but panics if an error occurs.
func (qhq *QuestionHistoryQuery) AllX(ctx context.Context) []*QuestionHistory {
	nodes, err := qhq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of QuestionHistory IDs.
func (qhq *QuestionHistoryQuery) IDs(ctx context.Context) (ids []int, err error) {
	if qhq.ctx.Unique == nil && qhq.path != nil {
		qhq.Unique(true)
	}
	ctx = setContextOp(ctx, qhq.ctx, "IDs")
	if err = qhq.Select(questionhistory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (qhq *QuestionHistoryQuery) IDsX(ctx context.Context) []int {
	ids, err := qhq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (qhq *QuestionHistoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, qhq.ctx, "Count")
	if err := qhq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, qhq, querierCount[*QuestionHistoryQuery](), qhq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (qhq *QuestionHistoryQuery) CountX(ctx context.Context) int {
	count, err := qhq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (qhq *QuestionHistoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, qhq.ctx, "Exist")
	switch _, err := qhq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (qhq *QuestionHistoryQuery) ExistX(ctx context.Context) bool {
	exist, err := qhq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the QuestionHistoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (qhq *QuestionHistoryQuery) Clone() *QuestionHistoryQuery {
	if qhq == nil {
		return nil
	}
	return &QuestionHistoryQuery{
		config:     qhq.config,
		ctx:        qhq.ctx.Clone(),
		order:      append([]questionhistory.OrderOption{}, qhq.order...),
		inters:     append([]Interceptor{}, qhq.inters...),
		predicates: append([]predicate.QuestionHistory{}, qhq.predicates...),
		// clone intermediate query.
		sql:  qhq.sql.Clone(),
		path: qhq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		HistoryTime time.Time `json:"history_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.QuestionHistory.Query().
//		GroupBy(questionhistory.FieldHistoryTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (qhq *QuestionHistoryQuery) GroupBy(field string, fields ...string) *QuestionHistoryGroupBy {
	qhq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &QuestionHistoryGroupBy{build: qhq}
	grbuild.flds = &qhq.ctx.Fields
	grbuild.label = questionhistory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		HistoryTime time.Time `json:"history_time,omitempty"`
//	}
//
//	client.QuestionHistory.Query().
//		Select(questionhistory.FieldHistoryTime).
//		Scan(ctx, &v)
func (qhq *QuestionHistoryQuery) Select(fields ...string) *QuestionHistorySelect {
	qhq.ctx.Fields = append(qhq.ctx.Fields, fields...)
	sbuild := &QuestionHistorySelect{QuestionHistoryQuery: qhq}
	sbuild.label = questionhistory.Label
	sbuild.flds, sbuild.scan = &qhq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a QuestionHistorySelect configured with the given aggregations.
func (qhq *QuestionHistoryQuery) Aggregate(fns ...AggregateFunc) *QuestionHistorySelect {
	return qhq.Select().Aggregate(fns...)
}

func (qhq *QuestionHistoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range qhq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, qhq); err != nil {
				return err
			}
		}
	}
	for _, f := range qhq.ctx.Fields {
		if !questionhistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if qhq.path != nil {
		prev, err := qhq.path(ctx)
		if err != nil {
			return err
		}
		qhq.sql = prev
	}
	return nil
}

func (qhq *QuestionHistoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*QuestionHistory, error) {
	var (
		nodes = []*QuestionHistory{}
		_spec = qhq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*QuestionHistory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &QuestionHistory{config: qhq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(qhq.modifiers) > 0 {
		_spec.Modifiers = qhq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, qhq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (qhq *QuestionHistoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := qhq.querySpec()
	if len(qhq.modifiers) > 0 {
		_spec.Modifiers = qhq.modifiers
	}
	_spec.Node.Columns = qhq.ctx.Fields
	if len(qhq.ctx.Fields) > 0 {
		_spec.Unique = qhq.ctx.Unique != nil && *qhq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, qhq.driver, _spec)
}

func (qhq *QuestionHistoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(questionhistory.Table, questionhistory.Columns, sqlgraph.NewFieldSpec(questionhistory.FieldID, field.TypeInt))
	_spec.From = qhq.sql
	if unique := qhq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if qhq.path != nil {
		_spec.Unique = true
	}
	if fields := qhq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, questionhistory.FieldID)
		for i := range fields {
			if fields[i] != questionhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := qhq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := qhq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := qhq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := qhq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (qhq *QuestionHistoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(qhq.driver.Dialect())
	t1 := builder.Table(questionhistory.Table)
	columns := qhq.ctx.Fields
	if len(columns) == 0 {
		columns = questionhistory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if qhq.sql != nil {
		selector = qhq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if qhq.ctx.Unique != nil && *qhq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range qhq.modifiers {
		m(selector)
	}
	for _, p := range qhq.predicates {
		p(selector)
	}
	for _, p := range qhq.order {
		p(selector)
	}
	if offset := qhq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := qhq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (qhq *QuestionHistoryQuery) ForUpdate(opts ...sql.LockOption) *QuestionHistoryQuery {
	if qhq.driver.Dialect() == dialect.Postgres {
		qhq.Unique(false)
	}
	qhq.modifiers = append(qhq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return qhq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (qhq *QuestionHistoryQuery) ForShare(opts ...sql.LockOption) *QuestionHistoryQuery {
	if qhq.driver.Dialect() == dialect.Postgres {
		qhq.Unique(false)
	}
	qhq.modifiers = append(qhq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return qhq
}

// QuestionHistoryGroupBy is the group-by builder for QuestionHistory entities.
type QuestionHistoryGroupBy struct {
	selector
	build *QuestionHistoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (qhgb *QuestionHistoryGroupBy) Aggregate(fns ...AggregateFunc) *QuestionHistoryGroupBy {
	qhgb.fns = append(qhgb.fns, fns...)
	return qhgb
}

// Scan applies the selector query and scans the result into the given value.
func (qhgb *QuestionHistoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, qhgb.build.ctx, "GroupBy")
	if err := qhgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuestionHistoryQuery, *QuestionHistoryGroupBy](ctx, qhgb.build, qhgb, qhgb.build.inters, v)
}

func (qhgb *QuestionHistoryGroupBy) sqlScan(ctx context.Context, root *QuestionHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(qhgb.fns))
	for _, fn := range qhgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*qhgb.flds)+len(qhgb.fns))
		for _, f := range *qhgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*qhgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := qhgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// QuestionHistorySelect is the builder for selecting fields of QuestionHistory entities.
type QuestionHistorySelect struct {
	*QuestionHistoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (qhs *QuestionHistorySelect) Aggregate(fns ...AggregateFunc) *QuestionHistorySelect {
	qhs.fns = append(qhs.fns, fns...)
	return qhs
}

// Scan applies the selector query and scans the result into the given value.
func (qhs *QuestionHistorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, qhs.ctx, "Select")
	if err := qhs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuestionHistoryQuery, *QuestionHistorySelect](ctx, qhs.QuestionHistoryQuery, qhs, qhs.inters, v)
}

func (qhs *QuestionHistorySelect) sqlScan(ctx context.Context, root *QuestionHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(qhs.fns))
	for _, fn := range qhs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*qhs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := qhs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
