// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Exam is the predicate function for exam builders.
type Exam func(*sql.Selector)

// ExamHistory is the predicate function for examhistory builders.
type ExamHistory func(*sql.Selector)

// Question is the predicate function for entquestion builders.
type Question func(*sql.Selector)

// QuestionHistory is the predicate function for questionhistory builders.
type QuestionHistory func(*sql.Selector)

// Quiz is the predicate function for quiz builders.
type Quiz func(*sql.Selector)

// QuizSubmission is the predicate function for quizsubmission builders.
type QuizSubmission func(*sql.Selector)
